<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.tomas-samek.examples</groupId>
        <artifactId>tiko-examples</artifactId>
        <version>0.2.1</version>
    </parent>

    <artifactId>05_multi_module</artifactId>
    <packaging>pom</packaging>
    <name>05 - Multi-Module Aggregation Example</name>

    <modules>
        <module>module-a</module>
        <module>module-b</module>
        <module>app</module>
    </modules>
</project>
