package io.tiko.processor.config;

import java.io.IOException;
import java.io.Writer;
import java.util.List;
import javax.annotation.processing.Filer;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

/**
 * Writes META-INF/tiko/configs.txt — one {@code <fqn>=<prefix>} per record — which maps each
 * record to its module's container and feeds tooling. Binders themselves are discovered through
 * the services file {@link ConfigBinderServicesWriter} writes (#531).
 */
public final class ConfigManifestWriter {

    private static final String PATH = "META-INF/tiko/configs.txt";

    private final Filer filer;
    private final String moduleRoot;

    /**
     * @param moduleRoot the main container's per-module directory (#537) to write a copy into, or
     *     {@code null} for test-compile output
     */
    public ConfigManifestWriter(Filer filer, String moduleRoot) {
        this.filer = filer;
        this.moduleRoot = moduleRoot;
    }

    public void write(List<ConfigurationModel> configs) throws IOException {
        if (configs.isEmpty()) return;
        writeTo(PATH, configs);
        if (moduleRoot != null) writeTo(moduleRoot + "configs.txt", configs);
    }

    private void writeTo(String path, List<ConfigurationModel> configs) throws IOException {
        FileObject f = filer.createResource(StandardLocation.CLASS_OUTPUT, "", path);
        try (Writer w = f.openWriter()) {
            w.write("# Auto-generated by tiko-processor — see tiko-config docs\n");
            for (ConfigurationModel cfg : configs) {
                w.write(cfg.qualifiedName());
                w.write("=");
                w.write(cfg.prefix());
                w.write("\n");
            }
        }
    }
}
