package io.tiko.processor.config;

import java.io.IOException;
import java.io.Writer;
import java.util.List;
import javax.annotation.processing.Filer;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

/**
 * Writes META-INF/tiko/configs.txt — one {@code <fqn>=<prefix>} per record,
 * preceded by a {@code # registry=<fqn>} header line so the runtime can locate
 * each module's per-module ConfigBinderRegistry_<hash> class.
 */
public final class ConfigManifestWriter {

    private static final String PATH = "META-INF/tiko/configs.txt";

    private final Filer filer;
    private final String registryFqn;

    public ConfigManifestWriter(Filer filer, String registryFqn) {
        this.filer = filer;
        this.registryFqn = registryFqn;
    }

    public void write(List<ConfigurationModel> configs) throws IOException {
        if (configs.isEmpty()) return;
        FileObject f = filer.createResource(StandardLocation.CLASS_OUTPUT, "", PATH);
        try (Writer w = f.openWriter()) {
            w.write("# Auto-generated by tiko-processor — see tiko-config docs\n");
            w.write("# registry=" + registryFqn + "\n");
            for (ConfigurationModel cfg : configs) {
                w.write(cfg.qualifiedName());
                w.write("=");
                w.write(cfg.prefix());
                w.write("\n");
            }
        }
    }
}
