package io.tiko.processor.config;

import java.io.IOException;
import java.io.Writer;
import java.util.List;
import javax.annotation.processing.Filer;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

/**
 * Writes META-INF/tiko/configs.txt — one {@code <fqn>=<prefix>} per record — which maps each
 * record to its module's container and feeds tooling. Binders themselves are discovered through
 * the services file {@link ConfigBinderServicesWriter} writes (#531).
 */
public final class ConfigManifestWriter {

    private static final String PATH = "META-INF/tiko/configs.txt";

    private final Filer filer;

    public ConfigManifestWriter(Filer filer) {
        this.filer = filer;
    }

    public void write(List<ConfigurationModel> configs) throws IOException {
        if (configs.isEmpty()) return;
        FileObject f = filer.createResource(StandardLocation.CLASS_OUTPUT, "", PATH);
        try (Writer w = f.openWriter()) {
            w.write("# Auto-generated by tiko-processor — see tiko-config docs\n");
            for (ConfigurationModel cfg : configs) {
                w.write(cfg.qualifiedName());
                w.write("=");
                w.write(cfg.prefix());
                w.write("\n");
            }
        }
    }
}
