package io.tiko.processor.config;

import java.io.IOException;
import java.io.Writer;
import java.util.List;
import javax.annotation.processing.Filer;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

/**
 * Writes {@code META-INF/services/io.tiko.config.ConfigBinder} listing this module's generated
 * binders, which {@code Tiko.create} discovers with {@link java.util.ServiceLoader} (#531). A
 * shaded fat jar's {@code ServicesResourceTransformer} merges every module's entries, where a
 * single-copy manifest would keep only one module's.
 */
public final class ConfigBinderServicesWriter {

    private static final String PATH = "META-INF/services/io.tiko.config.ConfigBinder";
    private static final String GENERATED_PACKAGE = "io.tiko.generated.config";

    private final Filer filer;

    public ConfigBinderServicesWriter(Filer filer) {
        this.filer = filer;
    }

    public void write(List<ConfigurationModel> configs) throws IOException {
        if (configs.isEmpty()) return;
        FileObject f = filer.createResource(StandardLocation.CLASS_OUTPUT, "", PATH);
        try (Writer w = f.openWriter()) {
            w.write("# Generated by tiko-processor: this module's @Configuration binders\n");
            for (ConfigurationModel cfg : configs) {
                w.write(GENERATED_PACKAGE + "." + cfg.binderSimpleName() + "\n");
            }
        }
    }
}
