package io.tiko.processor;

import com.google.auto.service.AutoService;
import io.tiko.EventTriggerGuard;
import io.tiko.Scope;
import io.tiko.annotations.*;
import io.tiko.processor.generator.*;
import io.tiko.processor.model.*;
import io.tiko.processor.util.ProcessorContext;
import io.tiko.processor.util.TypeUtil;
import io.tiko.processor.validation.*;
import java.util.*;
import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.MirroredTypeException;
import javax.lang.model.type.MirroredTypesException;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;

/**
 * Main annotation processor for Tiko DI.
 *
 * Processing stages:
 * 1. Scan and collect @Component, @Produces, @EventHandler annotations
 * 2. Build internal models (ComponentModel, FactoryMethodModel, EventHandlerModel)
 * 3. Validate dependency graph, circular dependencies, scope rules
 * 4. Generate code: factories, proxies, event registry, container
 */
@AutoService(Processor.class)
@SupportedSourceVersion(SourceVersion.RELEASE_21)
public final class TikoAnnotationProcessor extends AbstractProcessor {

    private ProcessorContext context;
    private TypeUtil typeUtil;
    private boolean processed = false;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);

        // Read active profiles from compiler options (e.g., -Atiko.profiles=dev,test)
        List<String> activeProfiles = parseActiveProfiles(processingEnv);

        this.context = new ProcessorContext(processingEnv, activeProfiles);
        this.typeUtil = new TypeUtil(processingEnv.getElementUtils(), processingEnv.getTypeUtils());
    }

    /**
     * FQN of the test-classpath shadow annotation. Referenced as a string to keep
     * tiko-processor free of any compile-time dependency on the optional test
     * support module that defines it; the annotation is detected reflectively at
     * processing time and silently ignored when absent.
     */
    private static final String TEST_COMPONENT_FQN = "io.tiko.test.TestComponent";

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return Set.of(
                Component.class.getCanonicalName(),
                Produces.class.getCanonicalName(),
                EventHandler.class.getCanonicalName(),
                Configuration.class.getCanonicalName(),
                TEST_COMPONENT_FQN);
    }

    @Override
    public Set<String> getSupportedOptions() {
        return Set.of("tiko.profiles", "tiko.topology.bundle");
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        // After generation, later rounds only process OUR generated (annotation-free)
        // sources — unless another processor emits new Tiko-annotated sources, which the
        // single-shot container cannot wire anymore. Make that loud instead of silent.
        if (processed) {
            if (!roundEnv.processingOver() && !annotations.isEmpty()) {
                processingEnv
                        .getMessager()
                        .printMessage(
                                Diagnostic.Kind.ERROR,
                                "Tiko DI: Tiko-annotated sources appeared in a later annotation-processing round"
                                        + " (generated by another processor?) after the container was generated."
                                        + " Tiko generates once per compilation — ensure all Tiko-annotated"
                                        + " sources are present in the original round.");
            }
            return false;
        }

        if (roundEnv.processingOver()) {
            // Nothing Tiko-relevant ever showed up. Generation happens in the round that
            // carries the annotations (#334): creating files here would trigger javac's
            // "created in the last round" warning per generated type and break -Werror.
            processingEnv
                    .getMessager()
                    .printMessage(
                            Diagnostic.Kind.WARNING,
                            "Tiko DI: No components, factories, or configurations found to process!");
            return false;
        }

        processingEnv
                .getMessager()
                .printMessage(Diagnostic.Kind.NOTE, "Tiko DI: Processing round, collecting annotations...");
        collectComponents(roundEnv);
        collectFactoryMethods(roundEnv);
        collectEventHandlers(roundEnv);
        collectConfigurations(roundEnv);

        processingEnv
                .getMessager()
                .printMessage(
                        Diagnostic.Kind.NOTE,
                        "Tiko DI: Collected " + context.getComponents().size() + " components, "
                                + context.getFactoryMethods().size()
                                + " factories, "
                                + context.getEventHandlers().size()
                                + " event handlers");

        // Nothing collected yet — a later round may still bring Tiko-annotated sources
        // generated by other processors; defer until something arrives.
        if (context.getComponents().isEmpty()
                && context.getFactoryMethods().isEmpty()
                && context.getConfigurations().isEmpty()) {
            return true; // Claim the annotations
        }

        // Validate and generate in THIS round (#334): the input set is complete for the
        // overwhelmingly common case (all user sources arrive in the first round), and
        // generating now keeps the final round file-free. Late-arriving Tiko sources are
        // rejected loudly by the processed-guard above.
        processed = true;

        processingEnv
                .getMessager()
                .printMessage(Diagnostic.Kind.NOTE, "Tiko DI: Starting validation and code generation...");

        try {

            processingEnv
                    .getMessager()
                    .printMessage(
                            Diagnostic.Kind.NOTE,
                            "Tiko DI: Found " + context.getComponents().size() + " components to process");

            // Stage 2: Validate
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Tiko DI: Starting validation...");
            if (!validate()) {
                // The validators have already emitted specific, located errors that fail the
                // compile — no generic trailer (it only added a content-free second error).
                return false;
            }
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Tiko DI: Validation passed");

            // In standalone test-compile, main @Component sources are absent from this round.
            // AmbiguityValidator's shadow detection requires both sides present, so it does not
            // fire when only the @TestComponent is visible. Bridge that gap by walking test
            // components whose testExtraKeys point at classpath-main FQNs and marking them as
            // shadows directly. Same-round detection still goes through AmbiguityValidator —
            // this only adds cross-round (peer-compile) shadow registration.
            markClasspathShadowedTestComponents();

            // Stage 3: Generate code
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Tiko DI: Starting code generation...");
            generate();

            processingEnv
                    .getMessager()
                    .printMessage(
                            Diagnostic.Kind.NOTE,
                            "Tiko DI: Successfully generated container with "
                                    + context.getComponents().size()
                                    + " components, "
                                    + context.getFactoryMethods().size()
                                    + " factories, "
                                    + context.getEventHandlers().size()
                                    + " event handlers");

        } catch (Exception e) {
            processingEnv
                    .getMessager()
                    .printMessage(Diagnostic.Kind.ERROR, "Tiko DI processing failed:\n" + formatStackTrace(e));
            return false;
        } finally {
            // Always emit the wiring-errors sibling artifact, even when validation or
            // code generation aborted. Downstream tooling (tiko-mcp's list_wiring_errors)
            // relies on the file being present on every processed round so a clean build
            // ships {"errors": []} and a broken build ships the structured failures.
            emitWiringErrors();
        }

        return true;
    }

    /**
     * Emits {@code META-INF/tiko/wiring-errors.json} via {@link io.tiko.processor.topology.WiringErrorsWriter}.
     * Gated on {@code -Atiko.topology.bundle=true} (the same opt-out as {@code topology.json}
     * and {@code config-schema.json}). Wrapped in its own try/catch so an IOException
     * during writer creation cannot mask a real processing failure earlier in the round.
     */
    private void emitWiringErrors() {
        if (!topologyBundleEnabled()) return;
        try {
            new io.tiko.processor.topology.WiringErrorsWriter(context.getWiringErrors())
                    .write(processingEnv.getFiler());
        } catch (java.io.IOException e) {
            processingEnv
                    .getMessager()
                    .printMessage(
                            Diagnostic.Kind.WARNING, "Tiko DI: failed to emit wiring-errors.json: " + e.getMessage());
        }
    }

    /**
     * Collects all @Component annotated classes, plus any @TestComponent classes when
     * the optional test-classpath annotation is present on the processor's classpath.
     */
    private void collectComponents(RoundEnvironment roundEnv) {
        for (Element element : roundEnv.getElementsAnnotatedWith(Component.class)) {
            if (!(element instanceof TypeElement typeElement)) {
                context.getErrorReporter()
                        .error(
                                element,
                                "@Component can only be applied to classes",
                                "Move @Component to a class declaration");
                continue;
            }

            ComponentModel component = buildComponentModel(typeElement);
            if (component != null) {
                context.registerComponent(component);
            }
        }

        // Test-classpath shadow annotation. Resolved by FQN so the processor stays
        // dependency-free of the optional support module and tolerates its absence in
        // production builds (lookup returns null → loop is skipped silently).
        TypeElement testComponentType = processingEnv.getElementUtils().getTypeElement(TEST_COMPONENT_FQN);
        if (testComponentType != null) {
            for (Element element : roundEnv.getElementsAnnotatedWith(testComponentType)) {
                if (!(element instanceof TypeElement typeElement)) {
                    context.getErrorReporter()
                            .error(
                                    element,
                                    "@TestComponent can only be applied to classes",
                                    "Move @TestComponent to a class declaration");
                    continue;
                }
                ComponentModel component = buildTestComponentModel(typeElement);
                if (component != null) {
                    context.registerComponent(component);
                }
            }
        }
    }

    /**
     * Builds a ComponentModel from a @Component annotated class.
     */
    private ComponentModel buildComponentModel(TypeElement typeElement) {
        Component annotation = typeElement.getAnnotation(Component.class);

        // Read @Component(expose = {...}) — uses the MirroredTypesException dance because
        // Class<?>[] annotation values are not directly accessible at processor time.
        List<TypeMirror> exposeTypes;
        try {
            annotation.expose();
            exposeTypes = List.of();
        } catch (MirroredTypesException mte) {
            exposeTypes = List.copyOf(mte.getTypeMirrors());
        }

        return buildComponentModel(
                typeElement,
                annotation.scope(),
                annotation.name(),
                Arrays.asList(annotation.profiles()),
                exposeTypes,
                annotation.exposeSelf(),
                false,
                "@Component",
                java.util.Set.of());
    }

    /**
     * Builds a ComponentModel from a class carrying the test-classpath shadow annotation.
     * Reads {@code scope} and {@code name} via {@link AnnotationMirror} traversal (string
     * FQN match) so the processor avoids a compile-time dependency on the support module
     * that declares the annotation. The remaining ComponentModel fields use the shadow
     * annotation's documented defaults (no profile gating, permissive exposure).
     */
    private ComponentModel buildTestComponentModel(TypeElement typeElement) {
        AnnotationMirror mirror = findAnnotationMirror(typeElement, TEST_COMPONENT_FQN);
        if (mirror == null) {
            // Element claimed by roundEnv but mirror missing — defensive guard, should not happen.
            return null;
        }

        Scope scope = readEnumAttribute(mirror, "scope", Scope.class).orElse(Scope.SINGLETON);
        String name = readStringAttribute(mirror, "name").orElse("");
        java.util.Set<String> extraKeys = computeTestExtraKeys(typeElement, mirror);

        return buildComponentModel(
                typeElement, scope, name, List.of(), List.of(), true, true, "@TestComponent", extraKeys);
    }

    private java.util.Set<String> computeTestExtraKeys(TypeElement testClass, AnnotationMirror mirror) {
        java.util.Optional<TypeMirror> valueAttr = readClassAttribute(mirror, "value");
        if (valueAttr.isPresent() && !isVoid(valueAttr.get())) {
            // Explicit value() wins over implicit walk. Verify the annotated class is
            // actually assignable to the declared value type, otherwise shadowing is
            // structurally impossible.
            TypeMirror valueType = valueAttr.get();
            if (!processingEnv.getTypeUtils().isAssignable(testClass.asType(), valueType)) {
                context.getErrorReporter()
                        .testComponentValueNotAssignable(
                                testClass, testClass.getQualifiedName().toString(), valueType.toString());
                return java.util.Set.of();
            }
            return java.util.Set.of(valueType.toString());
        }

        // Implicit walk: walk the superclass chain, returning routable types of the first
        // ancestor that is a main component. We check both (a) the @Component annotation
        // (visible when the main is being compiled in the same round) and (b) the
        // META-INF/tiko/components.txt manifest on the classpath (visible when the main
        // already lives in target/classes and only the test sources are being compiled).
        // The latter path is essential for the natural Maven layout where production
        // components and tests build in separate rounds.
        java.util.Set<String> mainComponentFqns = mainComponentFqnsOnClasspath();
        TypeMirror superMirror = testClass.getSuperclass();
        while (superMirror instanceof javax.lang.model.type.DeclaredType dt) {
            Element superElement = dt.asElement();
            if (!(superElement instanceof TypeElement superType)) break;
            if (superType.getQualifiedName().contentEquals("java.lang.Object")) break;

            boolean isMainComponent = superType.getAnnotation(io.tiko.annotations.Component.class) != null
                    || mainComponentFqns.contains(superType.getQualifiedName().toString());
            if (isMainComponent) {
                java.util.Set<String> keys = new java.util.LinkedHashSet<>();
                keys.add(superType.getQualifiedName().toString());
                for (TypeMirror iface : superType.getInterfaces()) {
                    keys.add(iface.toString());
                }
                return keys;
            }
            superMirror = superType.getSuperclass();
        }
        return java.util.Set.of();
    }

    /**
     * Marks any {@code @TestComponent} whose implicit-walk or explicit-value keys point at
     * a main {@code @Component} FQN listed in the classpath
     * {@code META-INF/tiko/components.txt} manifest. Bridges the gap left by
     * {@code AmbiguityValidator} in standalone test-compile rounds — main sources are not
     * present in the round, so the validator's shadow-pair detection (requires both sides
     * visible) cannot fire. Single-round compiles still rely on the validator path; this
     * helper only adds shadow entries the validator could not have seen.
     */
    private void markClasspathShadowedTestComponents() {
        java.util.Set<String> mainFqns = mainComponentFqnsOnClasspath();
        if (mainFqns.isEmpty()) {
            return;
        }
        for (var component : context.getActiveComponents()) {
            if (!component.isTestComponent()) continue;
            for (String extraKey : component.getTestExtraKeys()) {
                if (mainFqns.contains(extraKey)) {
                    context.markShadowedByTestOverride(extraKey, component);
                }
            }
        }
    }

    /**
     * Reads {@code META-INF/tiko/components.txt} from the compile classpath and returns
     * the set of main-component FQNs declared there. Empty when no such manifest exists
     * (e.g. the round is a first-emit main-compile rather than a peer test-compile).
     * Used by {@link #computeTestExtraKeys} so a {@code @TestComponent} can detect its
     * shadow target even when the production {@code @Component} sources are absent from
     * the round but already live on the classpath as compiled bytecode.
     */
    private java.util.Set<String> mainComponentFqnsOnClasspath() {
        try {
            var resource = processingEnv
                    .getFiler()
                    .getResource(javax.tools.StandardLocation.CLASS_PATH, "", "META-INF/tiko/components.txt");
            java.util.Set<String> fqns = new java.util.LinkedHashSet<>();
            try (var reader = new java.io.BufferedReader(resource.openReader(true))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    line = line.trim();
                    if (!line.isEmpty() && !line.startsWith("#")) {
                        fqns.add(line);
                    }
                }
            }
            return fqns;
        } catch (java.io.IOException e) {
            return java.util.Set.of();
        }
    }

    private static boolean isVoid(TypeMirror tm) {
        return tm.toString().equals("java.lang.Void");
    }

    /**
     * Shared model assembly for both {@code @Component} and the test-classpath shadow
     * annotation. Caller supplies annotation-derived attributes; this method handles
     * constructor / static-factory selection, lifecycle method discovery, proxy
     * decision, and builder population.
     */
    private ComponentModel buildComponentModel(
            TypeElement typeElement,
            Scope scope,
            String name,
            List<String> profiles,
            List<TypeMirror> exposeTypes,
            boolean exposeSelf,
            boolean isTestComponent,
            String annotationLabel,
            java.util.Set<String> testExtraKeys) {
        // Detect a self-@Produces method: a static @Produces method on this class
        // returning this class with the same qualifier name. When present, it acts
        // as the bean's instantiation strategy (replaces the constructor call).
        ExecutableElement staticFactoryMethod = findSelfStaticFactory(typeElement, name);

        ExecutableElement constructor;
        List<DependencyModel> dependencies;
        if (staticFactoryMethod != null) {
            // Static factory governs instantiation; constructor is optional.
            constructor = findInjectConstructor(typeElement); // may be null when private/multiple
            dependencies = buildDependencies(staticFactoryMethod);
        } else {
            // Standard path: require a usable constructor.
            constructor = findInjectConstructor(typeElement);
            if (constructor == null) {
                context.getErrorReporter()
                        .error(
                                typeElement,
                                annotationLabel
                                        + " must have an @Inject-annotated constructor or a single public constructor",
                                "Add @Inject annotation to a constructor",
                                "Ensure only one public constructor exists if not using @Inject",
                                "If instantiation goes through a static @Produces factory, no usable constructor is required");
                return null;
            }
            dependencies = buildDependencies(constructor);
        }

        // Find @PostConstruct and @PreDestroy methods
        List<ExecutableElement> postConstructMethods = findAnnotatedMethods(typeElement, PostConstruct.class);
        List<ExecutableElement> preDestroyMethods = findAnnotatedMethods(typeElement, PreDestroy.class);

        // Implicit AutoCloseable cleanup: when the component implements AutoCloseable and
        // the user did not declare an explicit @PreDestroy, the container codegen calls
        // close() at scope teardown. Explicit @PreDestroy always wins to avoid double-cleanup.
        boolean autoCloseable =
                preDestroyMethods.isEmpty() && typeUtil.implementsInterface(typeElement, "java.lang.AutoCloseable");

        // Check if component implements an interface (for proxy generation)
        Optional<TypeMirror> implementedInterface = typeUtil.getFirstInterface(typeElement);

        ComponentModel.Builder builder = ComponentModel.builder()
                .typeElement(typeElement)
                .packageName(typeUtil.getPackageName(typeElement))
                .className(typeElement.getSimpleName().toString())
                .qualifiedName(typeElement.getQualifiedName().toString())
                .scope(scope)
                .name(name)
                .profiles(profiles)
                .dependencies(dependencies)
                .postConstructMethods(postConstructMethods)
                .preDestroyMethods(preDestroyMethods)
                .autoCloseable(autoCloseable)
                .exposeTypes(exposeTypes)
                .exposeSelf(exposeSelf)
                .testComponent(isTestComponent)
                .testExtraKeys(testExtraKeys);

        if (constructor != null) {
            builder.constructor(constructor);
        }
        if (staticFactoryMethod != null) {
            builder.staticFactoryMethod(staticFactoryMethod);
        }

        implementedInterface.ifPresent(builder::implementedInterface);

        // Determine if proxy is needed (EVENT scope with interface)
        boolean needsProxy = scope == Scope.EVENT && implementedInterface.isPresent();
        builder.requiresProxy(needsProxy);

        return builder.build();
    }

    /**
     * Returns the {@link AnnotationMirror} on {@code element} whose annotation type has
     * the given canonical name, or {@code null} when none. Used for annotations the
     * processor must read without a compile-time dependency on the declaring module.
     */
    private AnnotationMirror findAnnotationMirror(Element element, String annotationFqn) {
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            Element declaring = mirror.getAnnotationType().asElement();
            if (declaring instanceof TypeElement typeElement
                    && typeElement.getQualifiedName().contentEquals(annotationFqn)) {
                return mirror;
            }
        }
        return null;
    }

    /**
     * Reads a string-valued annotation attribute by name. Returns empty when the
     * attribute is not present (defaults are not surfaced by
     * {@link Elements#getElementValuesWithDefaults(AnnotationMirror)} call sites
     * here — callers supply their own default).
     */
    private Optional<String> readStringAttribute(AnnotationMirror mirror, String attributeName) {
        Map<? extends ExecutableElement, ? extends AnnotationValue> values =
                processingEnv.getElementUtils().getElementValuesWithDefaults(mirror);
        for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : values.entrySet()) {
            if (entry.getKey().getSimpleName().contentEquals(attributeName)) {
                Object v = entry.getValue().getValue();
                return v instanceof String s ? Optional.of(s) : Optional.empty();
            }
        }
        return Optional.empty();
    }

    /**
     * Reads an enum-valued annotation attribute by name and resolves it to the matching
     * enum constant on {@code enumType}. Returns empty when the attribute is absent or
     * does not name a known constant.
     */
    private <E extends Enum<E>> Optional<E> readEnumAttribute(
            AnnotationMirror mirror, String attributeName, Class<E> enumType) {
        Map<? extends ExecutableElement, ? extends AnnotationValue> values =
                processingEnv.getElementUtils().getElementValuesWithDefaults(mirror);
        for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : values.entrySet()) {
            if (entry.getKey().getSimpleName().contentEquals(attributeName)) {
                Object v = entry.getValue().getValue();
                if (v instanceof VariableElement constant) {
                    try {
                        return Optional.of(
                                Enum.valueOf(enumType, constant.getSimpleName().toString()));
                    } catch (IllegalArgumentException ignored) {
                        return Optional.empty();
                    }
                }
                return Optional.empty();
            }
        }
        return Optional.empty();
    }

    /**
     * Reads a {@code Class<?>} annotation attribute as a {@link TypeMirror}. Annotation
     * {@code Class<?>} values are mirrored at processor time — direct {@code Class.getName()}
     * access throws {@link MirroredTypeException}, so the value must be extracted via the
     * AnnotationValue API.
     *
     * @return the attribute's TypeMirror, or empty when the attribute is absent.
     */
    private Optional<TypeMirror> readClassAttribute(AnnotationMirror mirror, String attributeName) {
        Map<? extends ExecutableElement, ? extends AnnotationValue> values =
                processingEnv.getElementUtils().getElementValuesWithDefaults(mirror);
        for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : values.entrySet()) {
            if (entry.getKey().getSimpleName().contentEquals(attributeName)) {
                Object v = entry.getValue().getValue();
                if (v instanceof TypeMirror tm) {
                    return Optional.of(tm);
                }
                return Optional.empty();
            }
        }
        return Optional.empty();
    }

    /**
     * Finds the constructor to use for injection. Selection rule:
     *   1. an @Inject-annotated constructor (any visibility) wins; or
     *   2. the sole public constructor when no @Inject is present.
     * Constructors that are not public and not @Inject-annotated are ignored — their
     * parameters are not injection points (issue #7).
     */
    private ExecutableElement findInjectConstructor(TypeElement typeElement) {
        List<ExecutableElement> publicConstructors = new ArrayList<>();
        ExecutableElement injectConstructor = null;

        for (Element element : typeElement.getEnclosedElements()) {
            if (element.getKind() != ElementKind.CONSTRUCTOR) continue;
            ExecutableElement constructor = (ExecutableElement) element;

            if (constructor.getAnnotation(Inject.class) != null) {
                if (injectConstructor != null) {
                    context.getErrorReporter()
                            .error(
                                    typeElement,
                                    "Multiple constructors annotated with @Inject",
                                    "Annotate exactly one constructor with @Inject",
                                    "Remove @Inject from the extra constructor(s)");
                    return null;
                }
                injectConstructor = constructor;
            }

            if (constructor.getModifiers().contains(Modifier.PUBLIC)) {
                publicConstructors.add(constructor);
            }
        }

        if (injectConstructor != null) {
            return injectConstructor;
        }

        if (publicConstructors.size() == 1) {
            return publicConstructors.get(0);
        }

        return null;
    }

    /**
     * Builds dependency models from method/constructor parameters.
     */
    private List<DependencyModel> buildDependencies(ExecutableElement executable) {
        List<DependencyModel> dependencies = new ArrayList<>();

        for (VariableElement parameter : executable.getParameters()) {
            TypeMirror paramType = parameter.asType();
            String typeName = typeUtil.getQualifiedName(paramType);

            // Provider<T> and Picker<T> are wrappers around a base type T. They are
            // mutually exclusive (a parameter can't be both), so detect each and unwrap
            // to the inner T for downstream lookup / codegen.
            boolean isProvider = typeUtil.isProvider(paramType);
            boolean isPicker = !isProvider && typeUtil.isPicker(paramType);
            TypeMirror unwrappedType = null;

            if (isProvider) {
                unwrappedType = typeUtil.unwrapProvider(paramType).orElse(null);
                if (unwrappedType != null) {
                    typeName = typeUtil.getQualifiedName(unwrappedType);
                }
            } else if (isPicker) {
                unwrappedType = typeUtil.unwrapPicker(paramType).orElse(null);
                if (unwrappedType != null) {
                    typeName = typeUtil.getQualifiedName(unwrappedType);
                }
            }

            // Check for @Named qualifier
            String qualifier = "";
            Named namedAnnotation = parameter.getAnnotation(Named.class);
            if (namedAnnotation != null) {
                qualifier = namedAnnotation.value();
            }

            // Check for @Pick class-literal qualifier. Reading the Class value goes
            // through MirroredTypeException because the picked class is a TypeMirror
            // at processor time, not yet a loadable Class.
            TypeMirror pickedType = null;
            String pickedTypeName = null;
            Pick pickAnnotation = parameter.getAnnotation(Pick.class);
            if (pickAnnotation != null) {
                try {
                    pickAnnotation.value();
                } catch (MirroredTypeException e) {
                    pickedType = e.getTypeMirror();
                }
                if (pickedType != null) {
                    pickedTypeName = typeUtil.getQualifiedName(pickedType);
                }
            }

            DependencyModel dependency = DependencyModel.builder()
                    .parameter(parameter)
                    .type(paramType)
                    .typeName(typeName)
                    .qualifier(qualifier)
                    .isProvider(isProvider)
                    .isPicker(isPicker)
                    .unwrappedType(unwrappedType)
                    .pickedType(pickedType)
                    .pickedTypeName(pickedTypeName)
                    .build();

            dependencies.add(dependency);
        }

        return dependencies;
    }

    /**
     * Finds all methods annotated with the given annotation.
     */
    private List<ExecutableElement> findAnnotatedMethods(TypeElement typeElement, Class<?> annotationClass) {
        List<ExecutableElement> methods = new ArrayList<>();

        for (Element element : typeElement.getEnclosedElements()) {
            if (element.getKind() == ElementKind.METHOD) {
                ExecutableElement method = (ExecutableElement) element;
                if (method.getAnnotation(annotationClass.asSubclass(java.lang.annotation.Annotation.class)) != null) {
                    methods.add(method);
                }
            }
        }

        return methods;
    }

    /**
     * Collects all @Produces factory methods.
     */
    private void collectFactoryMethods(RoundEnvironment roundEnv) {
        for (Element element : roundEnv.getElementsAnnotatedWith(Produces.class)) {
            if (!(element instanceof ExecutableElement methodElement)) {
                context.getErrorReporter()
                        .error(
                                element,
                                "@Produces can only be applied to methods",
                                "Move @Produces to a method that returns the produced type");
                continue;
            }

            // Skip a self-@Produces method already absorbed by its @Component model
            // (static method on the component class returning that class with matching qualifier).
            if (isSelfStaticFactory(methodElement)) {
                continue;
            }

            FactoryMethodModel factory = buildFactoryMethodModel(methodElement);
            if (factory != null) {
                context.registerFactoryMethod(factory);
            }
        }
    }

    /**
     * Returns the static @Produces method on {@code typeElement} that returns the same
     * type with a qualifier matching {@code componentName}, if present. Used so the
     * factory method becomes the component's instantiation strategy instead of a
     * competing provider.
     */
    private ExecutableElement findSelfStaticFactory(TypeElement typeElement, String componentName) {
        for (Element element : typeElement.getEnclosedElements()) {
            if (element.getKind() != ElementKind.METHOD) continue;
            ExecutableElement method = (ExecutableElement) element;
            Produces produces = method.getAnnotation(Produces.class);
            if (produces == null) continue;
            if (!method.getModifiers().contains(Modifier.STATIC)) continue;
            if (!processingEnv.getTypeUtils().isSameType(method.getReturnType(), typeElement.asType())) continue;
            if (!Objects.equals(produces.name(), componentName)) continue;
            return method;
        }
        return null;
    }

    /**
     * Predicate form of {@link #findSelfStaticFactory} for use during factory collection.
     */
    private boolean isSelfStaticFactory(ExecutableElement methodElement) {
        if (!methodElement.getModifiers().contains(Modifier.STATIC)) return false;
        Element enclosing = methodElement.getEnclosingElement();
        if (!(enclosing instanceof TypeElement declaringType)) return false;
        Component componentAnnotation = declaringType.getAnnotation(Component.class);
        if (componentAnnotation == null) return false;
        if (!processingEnv.getTypeUtils().isSameType(methodElement.getReturnType(), declaringType.asType()))
            return false;
        Produces produces = methodElement.getAnnotation(Produces.class);
        return produces != null && Objects.equals(produces.name(), componentAnnotation.name());
    }

    /**
     * Builds a FactoryMethodModel from a @Produces method.
     */
    private FactoryMethodModel buildFactoryMethodModel(ExecutableElement methodElement) {
        Produces annotation = methodElement.getAnnotation(Produces.class);
        TypeElement declaringClass = (TypeElement) methodElement.getEnclosingElement();

        TypeMirror returnType = methodElement.getReturnType();
        String returnTypeName = typeUtil.getQualifiedName(returnType);

        // Build dependencies from method parameters
        List<DependencyModel> dependencies = buildDependencies(methodElement);

        // Factory-produced beans implementing AutoCloseable get implicit close() at teardown,
        // covering the common case of @Produces returning third-party types (HikariDataSource,
        // HttpClient, KafkaProducer, etc.).
        boolean factoryAutoCloseable = typeUtil.isAssignableTo(returnType, "java.lang.AutoCloseable");

        // Auto-proxy: when an EVENT-scoped factory produces an interface, a longer-lived
        // consumer (SINGLETON injecting an EVENT-scoped Connection, for example) needs a proxy
        // that resolves to the current scope's value on every method call — same teaching as
        // @Component-based cross-scope proxies. Proxying a concrete class would require bytecode
        // tricks Tiko deliberately avoids, so we only emit a proxy for interface returns.
        boolean requiresProxy = annotation.scope() == Scope.EVENT
                && returnType.getKind() == javax.lang.model.type.TypeKind.DECLARED
                && ((javax.lang.model.type.DeclaredType) returnType).asElement().getKind()
                        == javax.lang.model.element.ElementKind.INTERFACE;

        return FactoryMethodModel.builder()
                .methodElement(methodElement)
                .declaringClass(declaringClass)
                .methodName(methodElement.getSimpleName().toString())
                .returnType(returnType)
                .returnTypeName(returnTypeName)
                .scope(annotation.scope())
                .name(annotation.name())
                .profiles(Arrays.asList(annotation.profiles()))
                .dependencies(dependencies)
                .autoCloseable(factoryAutoCloseable)
                .requiresProxy(requiresProxy)
                .build();
    }

    /**
     * Collects all @EventHandler methods.
     */
    private void collectEventHandlers(RoundEnvironment roundEnv) {
        for (Element element : roundEnv.getElementsAnnotatedWith(EventHandler.class)) {
            if (!(element instanceof ExecutableElement methodElement)) {
                context.getErrorReporter()
                        .error(
                                element,
                                "@EventHandler can only be applied to methods",
                                "Move @EventHandler to a method that takes the event as its first parameter");
                continue;
            }

            EventHandlerModel handler = buildEventHandlerModel(methodElement);
            if (handler != null) {
                context.registerEventHandler(handler);
            }
        }
    }

    /**
     * Collects all @Configuration records.
     */
    private void collectConfigurations(RoundEnvironment roundEnv) {
        new io.tiko.processor.config.ConfigurationCollector(context).collect(roundEnv);
    }

    /**
     * Builds an EventHandlerModel from an @EventHandler method.
     */
    private EventHandlerModel buildEventHandlerModel(ExecutableElement methodElement) {
        EventHandler annotation = methodElement.getAnnotation(EventHandler.class);
        TypeElement declaringClass = (TypeElement) methodElement.getEnclosingElement();

        List<? extends VariableElement> parameters = methodElement.getParameters();
        if (parameters.isEmpty()) {
            context.getErrorReporter()
                    .error(
                            methodElement,
                            "@EventHandler method must have at least one parameter (the event)",
                            "Add the event type as the method's first parameter");
            return null;
        }

        // First parameter is the event type
        TypeMirror eventType = parameters.get(0).asType();
        String eventTypeName = typeUtil.getQualifiedName(eventType);

        // Check if second parameter is Event<?> wrapper
        boolean hasEventWrapper = parameters.size() > 1
                && typeUtil.getQualifiedName(parameters.get(1).asType()).equals("io.tiko.Event");

        List<EventTriggerModel> eventTriggers = collectEventTriggers(methodElement);

        return EventHandlerModel.builder()
                .methodElement(methodElement)
                .declaringClass(declaringClass)
                .methodName(methodElement.getSimpleName().toString())
                .eventType(eventType)
                .eventTypeName(eventTypeName)
                .async(annotation.async())
                .hasEventWrapper(hasEventWrapper)
                .eventTriggers(eventTriggers)
                .build();
    }

    /**
     * Pulls every {@code @EventTrigger} annotation off a method (handles the implicit
     * {@code @EventTriggers} container that the compiler synthesises when the user
     * declares multiple). Default {@code AlwaysAllow} guards are dropped — codegen
     * treats an empty guard list as "always allow".
     */
    private List<EventTriggerModel> collectEventTriggers(ExecutableElement methodElement) {
        List<EventTrigger> raw = new ArrayList<>();
        EventTriggers container = methodElement.getAnnotation(EventTriggers.class);
        if (container != null) {
            raw.addAll(Arrays.asList(container.value()));
        } else {
            EventTrigger single = methodElement.getAnnotation(EventTrigger.class);
            if (single != null) raw.add(single);
        }

        String alwaysAllowName = EventTriggerGuard.AlwaysAllow.class.getCanonicalName();
        List<EventTriggerModel> models = new ArrayList<>(raw.size());
        for (EventTrigger trigger : raw) {
            List<TypeMirror> guardMirrors;
            try {
                trigger.guard();
                guardMirrors = List.of();
            } catch (MirroredTypesException e) {
                guardMirrors = new ArrayList<>(e.getTypeMirrors());
            }
            // Strip the default AlwaysAllow so codegen can skip the guard call entirely.
            guardMirrors.removeIf(m -> typeUtil.getQualifiedName(m).equals(alwaysAllowName));

            models.add(EventTriggerModel.builder()
                    .eventName(trigger.eventName())
                    .async(trigger.async())
                    .spread(trigger.spread())
                    .guardClasses(guardMirrors)
                    .build());
        }
        return models;
    }

    /**
     * Validates the dependency graph.
     */
    private boolean validate() {
        boolean valid = true;

        // Structural shape checks run first and short-circuit (#333): the validators below
        // assume well-shaped models — e.g. a raw Provider dependency NPEs the moment any
        // of them reads its dependency key.
        if (!new ComponentShapeValidator(context, typeUtil).validate()) {
            return false;
        }

        // Validate scope rules
        ScopeValidator scopeValidator = new ScopeValidator(context);
        for (ComponentModel component : context.getActiveComponents()) {
            if (!scopeValidator.validate(component)) {
                valid = false;
            }
        }
        for (FactoryMethodModel factory : context.getActiveFactoryMethods()) {
            if (!scopeValidator.validate(factory)) {
                valid = false;
            }
        }

        // Validate @Produces method signatures the code generator can realize (no void /
        // primitive / non-public / abstract). Catches these before codegen so the user gets
        // one clean error instead of a cascade of javac errors on generated source.
        ProducesSignatureValidator producesValidator = new ProducesSignatureValidator(context);
        if (!producesValidator.validate()) {
            valid = false;
        }

        // Validate @Component(expose = {...}) entries are actually implemented.
        ExposureValidator exposureValidator = new ExposureValidator(context, typeUtil);
        if (!exposureValidator.validate()) {
            valid = false;
        }

        // Validate dependencies exist
        DependencyGraphValidator graphValidator = new DependencyGraphValidator(context, typeUtil);
        if (!graphValidator.validate()) {
            valid = false;
        }

        // Detect circular dependencies
        CircularDependencyDetector circularDetector = new CircularDependencyDetector(context);
        if (!circularDetector.validate()) {
            valid = false;
        }

        // Detect ambiguous unnamed providers (two+ @Components/@Produces for same type)
        AmbiguityValidator ambiguityValidator = new AmbiguityValidator(context);
        if (!ambiguityValidator.validate()) {
            valid = false;
        }

        // Validate Picker<T> injection points (warn-only — never fails the build, so no verdict)
        new PickerValidator(context).validate();

        // Validate @Pick usage on injection-point parameters
        PickValidator pickValidator = new PickValidator(context);
        if (!pickValidator.validate()) {
            valid = false;
        }

        // Validate @Configuration records
        io.tiko.processor.config.ConfigurationValidator configValidator =
                new io.tiko.processor.config.ConfigurationValidator(context, processingEnv.getTypeUtils());
        if (!configValidator.validate()) {
            valid = false;
        }

        // Closeable-field leak warning (warning only, never fails the build)
        new CloseableLeakValidator(context).validate();

        return valid;
    }

    /**
     * Generates all code.
     */
    private void generate() throws Exception {
        // Compute container class name first (needed by all generators)
        String containerClassName = computeContainerClassName();
        context.setContainerClassName(containerClassName);

        // Generate factory for each component
        ComponentFactoryGenerator factoryGenerator = new ComponentFactoryGenerator(context);
        for (ComponentModel component : context.getActiveComponents()) {
            processingEnv
                    .getMessager()
                    .printMessage(Diagnostic.Kind.NOTE, "Tiko DI: Generating factory for " + component.getClassName());
            factoryGenerator.generate(component);
        }

        // Generate proxies for cross-scope injection
        ProxyGenerator proxyGenerator = new ProxyGenerator(context);
        for (ComponentModel component : context.getActiveComponents()) {
            if (component.requiresProxy()) {
                processingEnv
                        .getMessager()
                        .printMessage(
                                Diagnostic.Kind.NOTE, "Tiko DI: Generating proxy for " + component.getClassName());
            }
            proxyGenerator.generate(component);
        }
        // Factory outputs that are interfaces in shorter-lived scopes also need proxies so
        // longer-lived consumers (e.g., SINGLETON repo injecting a REQUEST-scoped Connection)
        // resolve per-call to the current scope's value instead of capturing the first one.
        for (FactoryMethodModel factory : context.getActiveFactoryMethods()) {
            if (factory.requiresProxy()) {
                processingEnv
                        .getMessager()
                        .printMessage(
                                Diagnostic.Kind.NOTE,
                                "Tiko DI: Generating proxy for " + factory.getFactoryIdentifier());
                proxyGenerator.generate(factory);
            }
        }

        // Generate event registry
        processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Tiko DI: Generating event registry...");
        EventRegistryGenerator eventRegistryGenerator = new EventRegistryGenerator(context);
        eventRegistryGenerator.generate();

        // Generate per-record ConfigBinder classes
        io.tiko.processor.config.ConfigBinderGenerator configBinderGen =
                new io.tiko.processor.config.ConfigBinderGenerator(
                        processingEnv.getFiler(), processingEnv.getMessager());
        for (io.tiko.processor.config.ConfigurationModel cfg : context.getConfigurations()) {
            if (configBinderGen.canGenerate(cfg)) {
                configBinderGen.generate(cfg);
            }
        }

        // Generate ConfigBinderRegistry and configs.txt manifest
        List<io.tiko.processor.config.ConfigurationModel> configs = context.getConfigurations();
        // containerClassName already computed above; extract the hash suffix from it
        String hashSuffix = containerClassName.substring(containerClassName.lastIndexOf('_') + 1);
        io.tiko.processor.config.ConfigBinderRegistryGenerator regGen =
                new io.tiko.processor.config.ConfigBinderRegistryGenerator(processingEnv.getFiler(), hashSuffix);
        regGen.generate(configs);
        new io.tiko.processor.config.ConfigManifestWriter(processingEnv.getFiler(), regGen.registryClassFqn())
                .write(configs);

        // Emit machine-readable topology.json for AI agents / IDE tooling / doc generators
        // when the build has anything worth describing. Gated to avoid empty-file noise.
        // Suppressed entirely when -Atiko.topology.bundle=false (closed-source services, sensitive jars).
        if (topologyBundleEnabled()
                && (!context.getActiveComponents().isEmpty()
                        || !context.getActiveFactoryMethods().isEmpty()
                        || !context.getEventHandlers().isEmpty()
                        || !context.getConfigurations().isEmpty())) {
            new io.tiko.processor.topology.TopologyWriter(context).write(processingEnv.getFiler());
        }

        // Emit config-schema.json when @Configuration records are present
        if (topologyBundleEnabled() && !context.getConfigurations().isEmpty()) {
            new io.tiko.processor.topology.ConfigSchemaWriter(context).write(processingEnv.getFiler());
        }

        // Generate container (must be last)
        processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Tiko DI: Generating container...");
        ContainerGenerator containerGenerator = new ContainerGenerator(context);
        containerGenerator.generate();
    }

    /**
     * Returns true when the user has opted into topology emission (the default).
     * Set {@code -Atiko.topology.bundle=false} to suppress {@code topology.json} and
     * {@code config-schema.json} entirely (closed-source services, sensitive jars).
     */
    private boolean topologyBundleEnabled() {
        var v = processingEnv.getOptions().get("tiko.topology.bundle");
        return v == null || !v.equalsIgnoreCase("false");
    }

    /**
     * Parses active profiles from compiler options.
     */
    private List<String> parseActiveProfiles(ProcessingEnvironment processingEnv) {
        String profilesOption = processingEnv.getOptions().get("tiko.profiles");
        if (profilesOption == null || profilesOption.isBlank()) {
            return List.of();
        }
        return Arrays.asList(profilesOption.split(","));
    }

    /**
     * Computes a unique container class name based on component keys.
     * This ensures different modules generate different container class names.
     *
     * <p>When the round is a test-compile happening on top of an existing main
     * container (detected via {@link #mainDescriptorFqnOnClasspath()}), the emitted
     * container is a standalone test container that peers with the existing main
     * via {@code AggregatingContainer} at runtime — so its class name carries the
     * {@code TestContainerImpl_} prefix instead of {@code TikoContainerImpl_}. All
     * factories, proxies, and the event registry are then typed against this test
     * container, with no parallel main-container emission in the test-compile round.
     */
    private String computeContainerClassName() {
        // Create deterministic ID based on component names
        List<String> componentKeys = context.getActiveComponents().stream()
                .map(ComponentModel::getComponentKey)
                .sorted()
                .toList();

        int hash = Objects.hash(componentKeys.toArray());
        // Convert to positive hex string
        String suffix = Integer.toHexString(hash & 0x7FFFFFFF);

        String prefix = (mainDescriptorFqnOnClasspath().isPresent() && context.hasTestComponents())
                ? "TestContainerImpl_"
                : "TikoContainerImpl_";
        return prefix + suffix;
    }

    /**
     * Probes the compile classpath for an existing {@code META-INF/tiko/container.properties}.
     * Returns the main container's FQN if found, or empty if no main container is on the
     * classpath. Used by {@link #computeContainerClassName()} to decide whether the round
     * is a standalone test-compile (peer to an existing main) or a regular main-compile.
     */
    private Optional<String> mainDescriptorFqnOnClasspath() {
        try {
            var resource = processingEnv
                    .getFiler()
                    .getResource(javax.tools.StandardLocation.CLASS_PATH, "", "META-INF/tiko/container.properties");
            try (var reader = resource.openReader(true)) {
                var props = new java.util.Properties();
                props.load(reader);
                String fqn = props.getProperty("impl");
                return fqn == null || fqn.isBlank() ? Optional.empty() : Optional.of(fqn);
            }
        } catch (java.io.IOException e) {
            return Optional.empty();
        }
    }

    private static String formatStackTrace(Throwable t) {
        var sb = new StringBuilder();
        sb.append(t.getClass().getName());
        if (t.getMessage() != null) {
            sb.append(": ").append(t.getMessage());
        }
        for (var frame : t.getStackTrace()) {
            sb.append("\n  at ").append(frame);
        }
        var cause = t.getCause();
        if (cause != null && cause != t) {
            sb.append("\nCaused by: ").append(formatStackTrace(cause));
        }
        return sb.toString();
    }
}
