package io.tiko.config;

import java.util.Map;

/**
 * One per {@code @Configuration} record. Implementations are generated by
 * {@code tiko-processor} at compile time — users do not write these.
 */
public interface ConfigBinder<T> {
    /** The Java record type this binder produces. */
    Class<T> type();

    /** The YAML root prefix this binder consumes (matches {@code @Configuration#prefix}). */
    String prefix();

    /**
     * Walks {@code root} at {@link #prefix()}, binds, and returns the constructed
     * record. Errors are accumulated into {@code ctx} rather than thrown.
     */
    T bind(Map<String, Object> root, BindContext ctx);
}
