package io.tiko.kafka.runtime.integration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

import io.tiko.kafka.runtime.integration.fixtures.ItOrderPlaced;
import io.tiko.kafka.runtime.integration.fixtures.ItOrderRecorder;
import io.tiko.runtime.Tiko;
import io.tiko.runtime.TikoOptions;
import java.time.Duration;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.kafka.ConfluentKafkaContainer;
import org.testcontainers.utility.DockerImageName;

/**
 * Real-Kafka end-to-end: starts a Testcontainers broker, runs the published
 * KafkaTransportBootstrap (generated by tiko-kafka-processor from the IT fixtures) against
 * it, and asserts that publishing an {@link ItOrderPlaced} locally results in the event
 * reaching the local consumer via the real Kafka broker (sink → broker → source → handler).
 *
 * <p>The IT uses dedicated {@code It*} fixture classes (isolated in
 * {@code io.tiko.kafka.runtime.integration.fixtures}) so that the generated
 * {@code KafkaTransportBootstrap} and the {@code TikoContainerImpl} produced by this
 * compilation are completely independent from the unit-test fixture set, preventing any
 * pollution of the unit-test container graph.
 *
 * <p>Flow:
 * <ol>
 *   <li>{@code container.getEventBus().publish(new ItOrderPlaced("real-1", 99))} fires.</li>
 *   <li>{@code ItOrderRecorder} handles it locally (first, before the sink).</li>
 *   <li>The {@code KafkaTransportBootstrap} sink sends the payload to the
 *       {@code "it-orders"} topic on the Testcontainers broker.</li>
 *   <li>The {@code KafkaTransportBootstrap} source consumer (same consumer group as sink's
 *       producer for this single-JVM test) polls the {@code "it-orders"} topic, deserializes
 *       the record, and publishes a second {@code ItOrderPlaced} event locally.</li>
 *   <li>{@code ItOrderRecorder} handles the second event.</li>
 *   <li>The test asserts at least one {@code ItOrderPlaced("real-1", 99)} arrived.</li>
 * </ol>
 */
@Testcontainers
class KafkaRealBrokerRoundTripIT {

    @org.testcontainers.junit.jupiter.Container
    static final ConfluentKafkaContainer KAFKA =
            new ConfluentKafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:7.7.1"));

    @Test
    void produced_then_consumed_via_real_broker() {
        TikoOptions opts = TikoOptions.builder()
                .configSource(io.tiko.config.ConfigSources.fromMap(Map.of(
                        "tiko.kafka",
                        Map.of(
                                "bootstrap-servers", KAFKA.getBootstrapServers(),
                                "consumer-group", "kafka-it",
                                "serializer", "json",
                                "auto-offset-reset", "earliest"))))
                .build();

        try (io.tiko.Container container = Tiko.create(opts)) {
            // The KafkaTransportBootstrap is auto-discovered via ServiceLoader.
            // Publishing fires ItOrderRecorder locally AND the sink sends to Kafka.
            container.getEventBus().publish(new ItOrderPlaced("real-1", 99));

            ItOrderRecorder recorder = container.get(ItOrderRecorder.class);
            // Wait until the source consumer delivers the round-tripped event.
            await().atMost(Duration.ofSeconds(30))
                    .until(() ->
                            recorder.received.stream().anyMatch(o -> o.orderId().equals("real-1")));

            assertThat(recorder.received).anyMatch(o -> o.orderId().equals("real-1") && o.amount() == 99);
        }
    }
}
