package io.tiko.kafka.processor.generator;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import io.tiko.kafka.processor.model.KafkaSinkDescriptor;
import io.tiko.kafka.processor.model.KafkaSourceDescriptor;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.util.List;
import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import javax.tools.StandardLocation;

/**
 * Emits one {@code io.tiko.generated.KafkaTransportBootstrap} class per compilation unit
 * plus the matching {@code META-INF/services/io.tiko.TransportBootstrap} entry.
 *
 * <p>The generated class implements {@link io.tiko.kafka.KafkaTransport} (which extends
 * {@link io.tiko.TransportBootstrap}). {@code start(Container)} resolves bridge components via
 * {@code container.get(...)}, looks up the {@code KafkaConfig} record, resolves serializers via
 * {@code ServiceLoader<NamedKafkaSerializer>}, subscribes one EventBus callback per sink, and
 * launches one consumer thread per source. {@code shutdown()} signals the threads to stop and
 * closes the producer / consumers.
 */
public final class KafkaTransportBootstrapGenerator {

    private static final String GENERATED_PACKAGE = "io.tiko.generated";
    private static final String CLASS_NAME = "KafkaTransportBootstrap";

    private static final ClassName GENERATED = ClassName.get("javax.annotation.processing", "Generated");
    private static final ClassName KAFKA_TRANSPORT = ClassName.get("io.tiko.kafka", "KafkaTransport");
    private static final ClassName CONTAINER = ClassName.get("io.tiko", "Container");
    private static final ClassName KAFKA_BOOTSTRAP_SUPPORT =
            ClassName.get("io.tiko.kafka.runtime", "KafkaBootstrapSupport");
    private static final ClassName KAFKA_SOURCE_DESCRIPTOR =
            ClassName.get("io.tiko.kafka.runtime", "GeneratedSourceDescriptor");
    private static final ClassName KAFKA_SINK_DESCRIPTOR =
            ClassName.get("io.tiko.kafka.runtime", "GeneratedSinkDescriptor");

    private final ProcessingEnvironment env;

    public KafkaTransportBootstrapGenerator(ProcessingEnvironment env) {
        this.env = env;
    }

    public void generate(List<KafkaSourceDescriptor> sources, List<KafkaSinkDescriptor> sinks) throws IOException {
        if (sources.isEmpty() && sinks.isEmpty()) return;

        // Inline @Generated rather than tiko-processor's GeneratorAnnotations helper:
        // this module deliberately has no compile dependency on tiko-processor (the two
        // processors run side-by-side on the user's annotation-processor path).
        TypeSpec.Builder cls = TypeSpec.classBuilder(CLASS_NAME)
                .addAnnotation(AnnotationSpec.builder(GENERATED)
                        .addMember("value", "$S", KafkaTransportBootstrapGenerator.class.getName())
                        .build())
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(KAFKA_TRANSPORT)
                .addField(KAFKA_BOOTSTRAP_SUPPORT, "support", Modifier.PRIVATE)
                .addJavadoc("Generated by tiko-kafka-processor. Do not edit.\n");

        cls.addMethod(buildStartMethod(sources, sinks));
        cls.addMethod(buildShutdownMethod());

        cls.addMethod(buildSourcesProvider(sources));
        cls.addMethod(buildSinksProvider(sinks));

        // Per-source dispatcher method: takes the resolved component + payload + ctx; invokes the bridge.
        for (int i = 0; i < sources.size(); i++) {
            cls.addMethod(buildSourceDispatcher(sources.get(i), i));
        }
        // Per-sink dispatcher method: takes the resolved component + event; returns the serialised payload.
        for (int i = 0; i < sinks.size(); i++) {
            cls.addMethod(buildSinkDispatcher(sinks.get(i), i));
        }
        // Per-sink key extractor: compile-time replacement for the former runtime reflection
        // on @KafkaSink(partitionKey) — the accessor was already validated by PartitionKeyValidator.
        for (int i = 0; i < sinks.size(); i++) {
            if (!sinks.get(i).partitionKey().isEmpty()) {
                cls.addMethod(buildSinkKeyExtractor(sinks.get(i), i));
            }
        }

        JavaFile.builder(GENERATED_PACKAGE, cls.build()).build().writeTo(env.getFiler());

        writeServiceLoaderEntry(env.getFiler());
    }

    private MethodSpec buildStartMethod(List<KafkaSourceDescriptor> sources, List<KafkaSinkDescriptor> sinks) {
        // Idempotency guard (#307): TransportBootstrap documents that a second start() has no
        // effect. Without it, re-starting replaced a live support with a fresh one — new
        // producer + consumer threads — while the old one kept running, unreachable and never
        // shut down. Mirrors the null-guard shutdown() already has.
        return MethodSpec.methodBuilder("start")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .addParameter(CONTAINER, "container")
                .beginControlFlow("if (this.support != null)")
                .addStatement("return")
                .endControlFlow()
                .addStatement("this.support = new $T(container, sources(), sinks())", KAFKA_BOOTSTRAP_SUPPORT)
                .addStatement("this.support.start()")
                .build();
    }

    private MethodSpec buildShutdownMethod() {
        return MethodSpec.methodBuilder("shutdown")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .beginControlFlow("if (this.support != null)")
                .addStatement("this.support.shutdown()")
                .addStatement("this.support = null")
                .endControlFlow()
                .build();
    }

    private MethodSpec buildSourcesProvider(List<KafkaSourceDescriptor> sources) {
        TypeName listOfDescriptors =
                ParameterizedTypeName.get(ClassName.get(java.util.List.class), KAFKA_SOURCE_DESCRIPTOR);
        MethodSpec.Builder b = MethodSpec.methodBuilder("sources")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(listOfDescriptors);

        if (sources.isEmpty()) {
            b.addStatement("return $T.of()", java.util.List.class);
            return b.build();
        }

        b.addStatement(
                "$T<$T> list = new $T<>()", java.util.List.class, KAFKA_SOURCE_DESCRIPTOR, java.util.ArrayList.class);
        for (int i = 0; i < sources.size(); i++) {
            KafkaSourceDescriptor s = sources.get(i);
            b.addStatement(
                    "list.add(new $T($S, $S, $S, $T.class, $T.class, $L, this::source$L))",
                    KAFKA_SOURCE_DESCRIPTOR,
                    s.topic(),
                    s.consumerGroup(),
                    s.eventName(),
                    TypeName.get(s.payloadType()),
                    TypeName.get(s.serializerClass()),
                    s.wantsKafkaContext(),
                    i);
        }
        b.addStatement("return list");
        return b.build();
    }

    private MethodSpec buildSinksProvider(List<KafkaSinkDescriptor> sinks) {
        TypeName listOfDescriptors =
                ParameterizedTypeName.get(ClassName.get(java.util.List.class), KAFKA_SINK_DESCRIPTOR);
        MethodSpec.Builder b = MethodSpec.methodBuilder("sinks")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(listOfDescriptors);

        if (sinks.isEmpty()) {
            b.addStatement("return $T.of()", java.util.List.class);
            return b.build();
        }

        b.addStatement(
                "$T<$T> list = new $T<>()", java.util.List.class, KAFKA_SINK_DESCRIPTOR, java.util.ArrayList.class);
        for (int i = 0; i < sinks.size(); i++) {
            KafkaSinkDescriptor s = sinks.get(i);
            if (s.partitionKey().isEmpty()) {
                b.addStatement(
                        "list.add(new $T($S, $S, $T.class, $T.class, this::sink$L, p -> null))",
                        KAFKA_SINK_DESCRIPTOR,
                        s.topic(),
                        s.partitionKey(),
                        TypeName.get(s.eventType()),
                        TypeName.get(s.serializerClass()),
                        i);
            } else {
                b.addStatement(
                        "list.add(new $T($S, $S, $T.class, $T.class, this::sink$L, $L::key$L))",
                        KAFKA_SINK_DESCRIPTOR,
                        s.topic(),
                        s.partitionKey(),
                        TypeName.get(s.eventType()),
                        TypeName.get(s.serializerClass()),
                        i,
                        CLASS_NAME,
                        i);
            }
        }
        b.addStatement("return list");
        return b.build();
    }

    private MethodSpec buildSourceDispatcher(KafkaSourceDescriptor s, int index) {
        ClassName bridgeClass = ClassName.get(s.enclosingClass());
        TypeName payloadName = TypeName.get(s.payloadType());

        MethodSpec.Builder b = MethodSpec.methodBuilder("source" + index)
                .addModifiers(Modifier.PRIVATE)
                .returns(Object.class)
                .addParameter(CONTAINER, "container")
                .addParameter(Object.class, "payload")
                .addParameter(ClassName.get("io.tiko.kafka", "KafkaContext"), "ctx");

        b.addStatement("$T bridge = container.get($T.class)", bridgeClass, bridgeClass);
        if (s.wantsKafkaContext()) {
            b.addStatement("return bridge.$L(($T) payload, ctx)", s.method().getSimpleName(), payloadName);
        } else {
            b.addStatement("return bridge.$L(($T) payload)", s.method().getSimpleName(), payloadName);
        }
        return b.build();
    }

    private MethodSpec buildSinkDispatcher(KafkaSinkDescriptor s, int index) {
        ClassName bridgeClass = ClassName.get(s.enclosingClass());
        TypeName eventName = TypeName.get(s.eventType());

        MethodSpec.Builder b = MethodSpec.methodBuilder("sink" + index)
                .addModifiers(Modifier.PRIVATE)
                .returns(Object.class)
                .addParameter(CONTAINER, "container")
                .addParameter(Object.class, "event");

        b.addStatement("$T bridge = container.get($T.class)", bridgeClass, bridgeClass);
        b.addStatement("return bridge.$L(($T) event)", s.method().getSimpleName(), eventName);
        return b.build();
    }

    private MethodSpec buildSinkKeyExtractor(KafkaSinkDescriptor s, int index) {
        TypeName payloadName = TypeName.get(s.producedPayloadType());
        return MethodSpec.methodBuilder("key" + index)
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                .returns(String.class)
                .addParameter(Object.class, "p")
                // Object (not var): the accessor may return a primitive, which must box
                // before the null check.
                .addStatement("$T v = (($T) p).$L()", Object.class, payloadName, s.partitionKey())
                .addStatement("return v == null ? null : $T.valueOf(v)", String.class)
                .build();
    }

    private void writeServiceLoaderEntry(Filer filer) throws IOException {
        var resource =
                filer.createResource(StandardLocation.CLASS_OUTPUT, "", "META-INF/services/io.tiko.TransportBootstrap");
        try (Writer w = new OutputStreamWriter(resource.openOutputStream(), StandardCharsets.UTF_8)) {
            w.write(GENERATED_PACKAGE + "." + CLASS_NAME);
            w.write("\n");
        }
    }
}
